baseURL = "https://hotchemi.github.io"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "etch"
title = "hotchemi.github.io"
enableRobotsTXT = true
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  unsafe = true
