baseURL = "https://hotchemi.github.io"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "minimal-bootstrap-hugo-theme"
title = "hotchemi.github.io"

[taxonomies]
  tag = "tags"

[params]
  contentBackgroundColor = "#fff"
  contentTextColor = "#333"
  contentLinkColor = "#256fba"
  contentLinkHoverColor = "#256fba"
  navbarBackgroundColor = "#fff"
  navbarLinkColor = "rgba(0, 0, 0, 0.6)"
  navbarLinkHoverColor = "rgba(0, 0, 0, 1.0)"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  cookieConsent = false
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 3

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2