baseURL = "https://hotchemi.github.io/"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "hugo-journal"
title = "hotchemi.github.io"
copyright = "Copyright (c) 2020, Shintaro Katafuchi; all rights reserved."

[params]
  	githubUsername = "hotchemi"
  	twitterUsername = "hotchemi"